### ISSUE TITLE
About the citation of the raydrop synthesis

### ISSUE THREAD

**Issue by kazuto1011** [hamedhaghighi/Lidar_intensity_modelling#1]
I came across your interesting work on arXiv! I noticed that the part about disentangling raydrop noises using Gumbel-Sigmoid bears a resemblance to [our work in IROS 2021](https://arxiv.org/abs/2102.11952). I would appreciate it if you could consider citing our work. Thank you.

**Comment by hamedhaghighi** [comment]
Thanks for raising that.  Actually, your work has heavily inspired ours.
For raydrop synthesis, we wanted to cite the original work that the idea
came from. We had another section that discussed unconditional models like
yours, but we removed it due to page constraints and forgot to mention it
later in the paper. So we will undoubtedly add a reference to your work in
our future revision of the paper.

**Comment by kazuto1011** [comment]
Thank you for your consideration.
